controller_list:
  - name: fake_left_arm_controller
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowPitch
  - name: fake_left_arm_torso_controller
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowPitch
  - name: fake_head_controller
    joints:
      - HeadYaw
      - HeadPitch
  - name: fake_right_arm_controller
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowPitch
  - name: fake_right_arm_torso_controller
    joints:
      - RShoulderPitch
      - RShoulderRoll
      - RElbowPitch
  - name: fake_whole_body_fixed_controller
    joints:
      - HeadYaw
      - HeadPitch
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll
      - LShoulderPitch
      - LShoulderRoll
      - LElbowPitch
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
      - RShoulderPitch
      - RShoulderRoll
      - RElbowPitch
  - name: fake_left_leg_controller
    joints:
      - LHipYaw
      - LHipRoll
      - LHipPitch
      - LKneePitch
      - LAnklePitch
      - LAnkleRoll
  - name: fake_right_leg_controller
    joints:
      - RHipYaw
      - RHipRoll
      - RHipPitch
      - RKneePitch
      - RAnklePitch
      - RAnkleRoll
  - name: fake_upper_body_controller
    joints:
      - LShoulderPitch
      - LShoulderRoll
      - LElbowPitch
      - RShoulderPitch
      - RShoulderRoll
      - RElbowPitch